### ISSUE TITLE
User rke deploy kubernetes

### ISSUE THREAD

**Issue by demoyuw** [demoyuw/k8s#8]
* download rke pakcage 
    * https://github.com/rancher/rke/releases/tag/v0.3.0-rc10/rke_linux-amd64
* Pre install
    * ssh-keygen
    * ssh-copy-id .ssh/id
    * ssh-copy-id -i .ssh/id_rsa localadmin@{k8s server}
    * sudo apt install docker.io
    * usermod -aG docker localadmin
* build cluster.yaml
```
---
nodes:
  - address: 192.168.100.1
    user: ubuntu
    role: [ controlplane,worker,etcd ]
  - address: 192.168.100.2
    user: ubuntu
    role: [ worker ]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

network:
    plugin: flannel
    options:
        flannel_iface: ens3
        flannel_backend_type: vxlan
```

* rke up

ref: https://rancher.com/docs/rke/latest/en/installation/#prepare-the-nodes-for-the-kubernetes-cluster
